name: Manage_Policy
on:
  pull_request:
    branches: [ "main" ]
       
permissions:
  contents: read    #possible values : None, Read, Write
  
jobs:
  manage-policy:
    runs-on: ubuntu-latest

    env:
      #ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      #ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login to NamanTyagi2610 Tenant
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan  -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" #-var "rg_name=my-rbac-rg" -var "sp_object_id=${{ secrets.SP_OBJECT_ID }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" #-var "rg_name=my-rbac-rg" -var "sp_object_id=${{ secrets.SP_OBJECT_ID }}"
